### ISSUE TITLE
Installation broken with latest Homebrew due to `livecheck` changes

### ISSUE THREAD

**Issue by karimbenbourenane** [epk/SF-Mono-Nerd-Font#5]
Recent changes to Homebrew require a different way of using the `livecheck` method in Cask formulae. When attempting to install, currently, output errors like this:

```
❯ brew install font-sf-mono-nerd-font 
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: Cask 'font-sf-mono-nerd-font' is unreadable: wrong number of arguments (given 1, expected 0)
==> Searching for similarly named formulae and casks...
Error: Cask 'font-sf-mono-nerd-font' is unreadable: wrong number of arguments (given 1, expected 0)
```

To fix this, I had to edit the formula for this Cask and modify this line:

`livecheck 'https://github.com/epk/SF-Mono-Nerd-Font/releases.atom'`

Instead, I use the following:

```
  livecheck do
    url :url
    strategy :github_latest
  end
```

This change allows installation to succeed.

**Comment by kkiani** [comment]
I am facing the same issue

**Comment by epk** [comment]
Fixed in https://github.com/epk/homebrew-epk/commit/3e2ad69d1e369818fd484c95ac3a3604ca33b901
